apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    app: search
  name: search
  namespace: default
  resourceVersion: "51984"
  selfLink: /apis/apps/v1/namespaces/default/deployments/search
  uid: 1cb9ad9e-e959-477f-80ed-7566b09e36d9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: search
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: search
    spec:
      containers:
      - image: kowshhal/search
        imagePullPolicy: Always
        name: search
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: search
    name: search
    namespace: default
    resourceVersion: "2363"
    selfLink: /api/v1/namespaces/default/services/search
    uid: b8f7da33-deca-4a7b-b636-b5cb101e46ff
  spec:
    clusterIP: 10.152.183.246
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30048
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: search
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
  
